### ISSUE TITLE
ちょっと遅れていくかもしれません

### ISSUE THREAD

**Issue by bathtimefish** [bathtimefish/web-and-car-hackathon#12]
朝からおなか痛くてトイレを行ったり来たりしています。
行くの9:30過ぎるかもしれません。とりあえずホテルで開発してます。

**Comment by kosuke-watanabe** [comment]
村岡さん

おはようございます。
渡辺です。

承知しました。
落ち着いたら現地でお会いしましょう。
お待ちしております。

2016年1月31日日曜日、Masakazu Muraokanotifications@github.comさんは書きました:

> 朝からおなか痛くてトイレを行ったり来たりしています。
> 行くの9:30過ぎるかもしれません。とりあえずホテルで開発してます。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bathtimefish/web-and-car-hackathon/issues/12.

## 

# 

FOX HOUND株式会社 渡辺康介
〒164-0001 東京都中野区中野5-24-18 クロススクエアNAKANO 704
TEL:(03)3388-6988
Email ： kosuke.watanabe@fox-hound.jp <E-MAIL%3Akosuke.watanabe@fox-hound.jp>

# URL ： http://fox-hound.co.jp/

**Comment by bathtimefish** [comment]
無事到着
